{% set name = "azure-mgmt-trafficmanager" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 4741761e80346c4edd4cb3f271368ea98063f804d015e245c2fe048ed2b596a8
  
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - msrest >=0.6.21
    - azure-common >=1.1,<2.0
    - azure-mgmt-core>=1.3.0,<2.0.0

test:
  imports:
    - azure.mgmt.trafficmanager
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Traffic Manager Client Library for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Microsoft Azure Traffic Manager Client Library for Python
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - tim-werner
